name: Lab01 Variables and Secrets
run-name: Lab01 - ${{ github.actor }} is testing variables and secrets 🚀
permissions: read-all
defaults:
  run:
    shell: pwsh
on:
  workflow_dispatch:
jobs:
  demo-job:
    runs-on: ubuntu-latest
    env:
      MY_VARIABLE: Hello, GitHub Actions!

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Echo variables and secrets
        env:
          DEMO_SECRET: ${{ secrets.DEMO_SECRET }}
        run: |
          echo "Environment variable: $env:MY_VARIABLE"
          echo "Secret value: $env:DEMO_SECRET"
          echo "Note how the secret value is not printed to the log"
