name: Lab02 Reuse and Artifacts
run-name: Lab02 - ${{ github.actor }} is calling Composite Actions 🚀
permissions: read-all
defaults:
  run:
    shell: pwsh
on:
  workflow_dispatch:
jobs:
  run-composite:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4
      # Run the template with parameters
      - id: dotnet-build
        uses: ./.github/actions/build-dotnet-app
        with:
          folder-path: apps/uptodate-app
      # Publish output folder as an artifact
      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ${{ steps.dotnet-build.outputs.output-directory-path }}
  greeter:
    uses: ./.github/workflows/greeter.yml
    with:
      person-name: "${{ github.actor }}"
